import { Project, Building, Unit, BankPreset } from '@/types/database';

export const initialProjects: Project[] = [
  {
    id: 'avan',
    slug: 'avan',
    name: 'ЖК Green Avan',
    district: 'Аван, Ереван',
    address: 'г. Ереван, Аван, ул. Царав Ахбюр, 61/4',
    category: 'Комфорт-плюс',
    floorsCount: 14,
    totalUnits: 112,
    readiness: '90%',
    deliveryDate: 'IV кв. 2025',
    priceFromAMD: 14060000,
    timeToCenter: '10 мин',
    image: '/images/apt-3.png',
    description: '14-этажный высотный комплекс комфорт-плюс с закрытым благоустроенным двором-садом, 2 скоростными лифтами и подземным паркингом.',
    acousticComfort: '55 дБ',
    seismicScore: '9 баллов СНиП РА',
    concreteGrade: 'B25/B30',
    taxRefundEligible: true,
    taxRefundType: 'phased',
    coordinates: { lat: 40.2195, lng: 44.5714 },
    features: [
      '2 бесшумных скоростных лифта',
      'Подземный двухуровневый паркинг',
      'Озелененная закрытая территория без машин',
      'Современная развивающая детская площадка',
      'Панорамное энергоэффективное остекление',
    ],
  },
  {
    id: 'nork',
    slug: 'nork',
    name: 'ЖК Green Nork',
    district: 'Нор-Норк, Ереван',
    address: 'г. Ереван, Нор-Норк, ул. Гюрджяна, 14',
    category: 'Бизнес-класс',
    floorsCount: 6,
    totalUnits: 36,
    readiness: '95%',
    deliveryDate: 'III кв. 2026',
    priceFromAMD: 33650000,
    timeToCenter: '15 мин',
    image: '/images/apt-2.png',
    description: 'Камерный 6-этажный клубный дом бизнес-класса с панорамным обзором горы Арарат, приватным лобби и акустической защитой 55 дБ.',
    acousticComfort: '55 дБ',
    seismicScore: '9 баллов СНиП РА',
    concreteGrade: 'B30 монолит',
    taxRefundEligible: true,
    taxRefundType: 'phased',
    coordinates: { lat: 40.1859, lng: 44.5514 },
    features: [
      'Всего 36 квартир в доме',
      'Прямой обзор библейской горы Арарат',
      'Премиальное дизайнерское лобби',
      'Повышенная звукоизоляция 55 дБ',
      'Подземный охраняемый паркинг',
    ],
  },
  {
    id: 'townhouse',
    slug: 'townhouse',
    name: 'Green Townhouse',
    district: 'с. Касах, Котайк',
    address: 'Котайкский марз, с. Касах, ул. Ованеса Туманяна, 12',
    category: 'Премиум таунхаусы',
    floorsCount: 2,
    totalUnits: 4,
    readiness: '85%',
    deliveryDate: 'IV кв. 2026',
    priceFromAMD: 45880000,
    timeToCenter: '11 км (12 мин до Площади Республики)',
    image: '/images/apt-5.png',
    description: '4 двухэтажных европейских таунхауса с индивидуальным земельным участком 124 м², открытой террасой на крыше и бессрочным возвратом подоходного налога.',
    acousticComfort: '55 дБ',
    seismicScore: '9 баллов СНиП РА',
    concreteGrade: 'B25 монолит',
    taxRefundEligible: true,
    taxRefundType: 'indefinite',
    coordinates: { lat: 40.2312, lng: 44.4765 },
    features: [
      'Собственный земельный участок 124 м²',
      'Индивидуальная открытая терраса',
      'Бессрочный возврат налога (Котайк)',
      'Индивидуальное парковочное место',
      'Автономное энергоэффективное отопление',
    ],
  },
];

export const initialBuildings: Building[] = [
  { id: 'bld-avan-1', projectId: 'avan', name: 'Корпус 1 (Секция А)', totalFloors: 14, address: 'ул. Царав Ахбюр, 61/4, Корпус 1' },
  { id: 'bld-avan-2', projectId: 'avan', name: 'Корпус 2 (Секция Б)', totalFloors: 14, address: 'ул. Царав Ахбюр, 61/4, Корпус 2' },
  { id: 'bld-nork-1', projectId: 'nork', name: 'Клубный корпус', totalFloors: 6, address: 'ул. Гюрджяна, 14' },
  { id: 'bld-th-1', projectId: 'townhouse', name: 'Линейка Таунхаусов (Блоки 1-4)', totalFloors: 2, address: 'ул. Ов. Туманяна, 12' },
];

export const initialUnits: Unit[] = [
  {
    id: 'avan-101',
    projectId: 'avan',
    buildingId: 'bld-avan-1',
    floorNumber: 4,
    unitNumber: '42',
    rooms: 1,
    roomsLabel: '1-комнатная (Студия)',
    areaSqm: 38.0,
    priceAMD: 14060000,
    status: 'available',
    image: '/images/apt-3.png',
    planSvgKey: 'plan-studio-38',
    ceilingHeight: 3.0,
    balconyArea: 3.8,
    viewDescription: 'Вид на зеленый внутренний парк',
    features: ['Гардеробная ниша', 'Французский балкон', 'Черновая стяжка со звукоизоляцией'],
    exactAddress: 'г. Ереван, Аван, ул. Царав Ахбюр, 61/4, корп. 1, кв. 42',
  },
  {
    id: 'avan-102',
    projectId: 'avan',
    buildingId: 'bld-avan-1',
    floorNumber: 6,
    unitNumber: '58',
    rooms: 1,
    roomsLabel: '1-комнатная',
    areaSqm: 42.0,
    priceAMD: 15540000,
    status: 'available',
    image: '/images/apt-4.png',
    planSvgKey: 'plan-1k-42',
    ceilingHeight: 3.0,
    balconyArea: 4.2,
    viewDescription: 'Юго-восточная сторона, панорама города',
    features: ['Просторная прихожая', 'Остекленная лоджия', 'Индивидуальные узлы учета'],
    exactAddress: 'г. Ереван, Аван, ул. Царав Ахбюр, 61/4, корп. 1, кв. 58',
  },
  {
    id: 'avan-103',
    projectId: 'avan',
    buildingId: 'bld-avan-1',
    floorNumber: 9,
    unitNumber: '86',
    rooms: 2,
    roomsLabel: '2-комнатная евро',
    areaSqm: 64.0,
    priceAMD: 23680000,
    status: 'reserved',
    image: '/images/apt-1.png',
    planSvgKey: 'plan-2k-64',
    ceilingHeight: 3.0,
    balconyArea: 5.6,
    viewDescription: 'Двусторонняя инсоляция, вид на парк и город',
    features: ['Кухня-гостиная 22 м²', 'Мастер-спальня', 'Раздельный санузел'],
    exactAddress: 'г. Ереван, Аван, ул. Царав Ахбюр, 61/4, корп. 1, кв. 86',
  },
  {
    id: 'avan-104',
    projectId: 'avan',
    buildingId: 'bld-avan-2',
    floorNumber: 11,
    unitNumber: '104',
    rooms: 3,
    roomsLabel: '3-комнатная семейная',
    areaSqm: 88.5,
    priceAMD: 32745000,
    status: 'sold',
    image: '/images/apt-6.png',
    planSvgKey: 'plan-3k-88',
    ceilingHeight: 3.0,
    balconyArea: 7.2,
    viewDescription: 'Вид на Аванские сады',
    features: ['2 санузла', 'Изолированная гардеробная', 'Широкая лоджия 7.2 м²'],
    exactAddress: 'г. Ереван, Аван, ул. Царав Ахбюр, 61/4, корп. 2, кв. 104',
  },
  {
    id: 'nork-201',
    projectId: 'nork',
    buildingId: 'bld-nork-1',
    floorNumber: 2,
    unitNumber: '08',
    rooms: 2,
    roomsLabel: '2-комнатная клубная',
    areaSqm: 58.0,
    priceAMD: 33650000,
    status: 'available',
    image: '/images/apt-2.png',
    planSvgKey: 'plan-2k-nork-58',
    ceilingHeight: 3.15,
    balconyArea: 5.0,
    viewDescription: 'Панорамный обзор Нор-Норка',
    features: ['Потолки 3.15 м', 'Звукоизоляция 55 дБ', 'Панорамные окна в пол'],
    exactAddress: 'г. Ереван, Нор-Норк, ул. Гюрджяна, 14, кв. 8',
  },
  {
    id: 'nork-202',
    projectId: 'nork',
    buildingId: 'bld-nork-1',
    floorNumber: 5,
    unitNumber: '24',
    rooms: 3,
    roomsLabel: '3-комнатная с видом на Арарат',
    areaSqm: 92.0,
    priceAMD: 53360000,
    status: 'available',
    image: '/images/apt-3.png',
    planSvgKey: 'plan-3k-nork-92',
    ceilingHeight: 3.15,
    balconyArea: 8.5,
    viewDescription: 'Прямой панорамный вид на гору Арарат',
    features: ['Видовая панорамная терраса', 'Входная сейф-дверь', 'Индивидуальная вентиляция'],
    exactAddress: 'г. Ереван, Нор-Норк, ул. Гюрджяна, 14, кв. 24',
  },
  {
    id: 'nork-203',
    projectId: 'nork',
    buildingId: 'bld-nork-1',
    floorNumber: 6,
    unitNumber: '32',
    rooms: 3,
    roomsLabel: 'Пентхаус с круговой панорамой',
    areaSqm: 110.0,
    priceAMD: 63800000,
    status: 'reserved',
    image: '/images/apt-1.png',
    planSvgKey: 'plan-penthouse-110',
    ceilingHeight: 3.3,
    balconyArea: 14.0,
    viewDescription: 'Круговой обзор 360° на Ереван и Арарат',
    features: ['Высота потолков 3.30 м', 'Круговая терраса 14 м²', 'Приватный лифтовой доступ'],
    exactAddress: 'г. Ереван, Нор-Норк, ул. Гюрджяна, 14, кв. 32',
  },
  {
    id: 'th-301',
    projectId: 'townhouse',
    buildingId: 'bld-th-1',
    floorNumber: 1,
    unitNumber: 'TH-01',
    rooms: 4,
    roomsLabel: 'Таунхаус 120 м² с участком',
    areaSqm: 120.0,
    priceAMD: 45880000,
    status: 'available',
    image: '/images/apt-5.png',
    planSvgKey: 'plan-th-120',
    ceilingHeight: 3.1,
    balconyArea: 16.0,
    viewDescription: 'Участок 124 м² и вид на гору Арагац',
    features: ['Свой земельный участок 124 м²', '2 этажа', 'Терраса на эксплуатируемой кровле', 'Паркоместо у входа'],
    exactAddress: 'Котайкский марз, с. Касах, ул. Ов. Туманяна, 12, Блок 1',
  },
  {
    id: 'th-302',
    projectId: 'townhouse',
    buildingId: 'bld-th-1',
    floorNumber: 1,
    unitNumber: 'TH-02',
    rooms: 4,
    roomsLabel: 'Таунхаус 141 м² угловой',
    areaSqm: 141.0,
    priceAMD: 53900000,
    status: 'available',
    image: '/images/apt-5.png',
    planSvgKey: 'plan-th-141',
    ceilingHeight: 3.1,
    balconyArea: 20.0,
    viewDescription: 'Увеличенный приватный двор и терраса',
    features: ['Угловой участок 160 м²', 'Каминный дымоход', 'Панорамные раздвижные двери'],
    exactAddress: 'Котайкский марз, с. Касах, ул. Ов. Туманяна, 12, Блок 2',
  },
];

export const initialBanks: BankPreset[] = [
  { id: 'ameria', name: 'Ameriabank', rate: 11.2, minDownPaymentPercent: 10, maxTermYears: 20, isPopular: true },
  { id: 'ineco', name: 'Inecobank', rate: 11.5, minDownPaymentPercent: 10, maxTermYears: 20, isPopular: true },
  { id: 'ardshin', name: 'Ardshinbank', rate: 11.0, minDownPaymentPercent: 10, maxTermYears: 25, isPopular: true },
  { id: 'acba', name: 'ACBA Bank', rate: 11.8, minDownPaymentPercent: 10, maxTermYears: 20 },
];
